trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: Npm@1
#   inputs:
#     command: 'install'
#     workingDir: '$(Build.Repository.LocalPath)'
#   displayName: 'npm install'
# - task: Npm@1
#   inputs: 
#     command: custom
#     workingDir: '$(Build.Repository.LocalPath)'
#     customCommand: 'audit fix'
#   displayName: 'npm audit fix'
# - task: Npm@1
#   inputs:
#     command: custom
#     workingDir: '$(Build.Repository.LocalPath)'
#     customCommand: 'run build:analyze'
#   displayName: 'npm run build:analyze'
# - task: Npm@1
#   inputs:
#     command: custom
#     workingDir: '$(Build.Repository.LocalPath)'
#     customCommand: 'run start'
#   displayName: 'npm run start'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/app/'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app/'
    ArtifactName: 'app'
    publishLocation: 'Container'
